import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "DEISI Next Apps",
  description: "Generated by DIW",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <header className="flex flex-col justify-center items-center gap-5 pt-10">
          <h1 className="text-4xl font-bold">Aula 2 de React.js</h1>
          <nav className="flex flex-row justify-center gap-10">
            <Link href="/counter">Counter</Link>
            <Link href="/municipalities">Municipalities</Link>
          </nav>
        </header>
        <main className="bg-white p-10 m-5 h-1/2 w-1/2">
          {children}
        </main>
      </body>
    </html>
  );
}
